tap "homebrew/bundle"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite"
# Download with resuming and segmented downloading
brew "aria2"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# OpenType text shaping engine
brew "harfbuzz"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line tools for fly.io services
brew "flyctl"
# Library for manipulating fonts
brew "fonttools"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Tool for glamorous shell scripts
brew "gum"
# Move files and folders to the trash
brew "macos-trash"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Port scanning utility for large networks
brew "nmap"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# CLI for extracting streams from various websites to a video player
brew "streamlink"
# Utilities to create and convert Web Open Font File (WOFF) files
brew "woff2"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Flexible and fast Zsh plugin manager
brew "zinit"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Screen saver based on animations presented during Apple Special Event Brooklyn
cask "brooklyn"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox@nightly"
cask "font-commit-mono-nerd-font"
# Font viewer for various font formats
cask "fontgoggles"
# Apple Mail plugin for GnuPG encrypted e-mails
cask "free-gpgmail"
# YouTube player focusing on privacy
cask "freetube"
# Web browser
cask "google-chrome@canary"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Tool to show what is persistently installed on the computer
cask "knockknock"
# Monitors and reports any microphone and camera activity
cask "micro-snitch"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Collection of apps available by subscription
cask "setapp"
# Instant messaging application focusing on security
cask "signal"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
