# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    auto_pause_after_reviewed_commits: 0

  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  pre_merge_checks:
    docstrings:
      mode: "off"
    title:
      mode: error
    description:
      mode: error

  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: true
  review_details: true

  path_filters:
    - "!.config/nvim/lazy-lock.json"

chat:
  auto_reply: false
