git:
  autoForwardBranches: none
  pagers:
    - pager: delta --detect-dark-light always --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --line-numbers --paging=never
      colorArg: always
gui:
  language: en
  nerdFontsVersion: "3"
  useHunkModeInStagingView: false
