git:
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: delta --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --line-numbers --paging=never
gui:
  language: en
  nerdFontsVersion: "3"
