# Disable most modules
[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_commit]
# Always show git commit hash
only_detached = false

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
format = "via [⬢ $version](bold green) "

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
# Enable displaying version for packages marked as private
display_private = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
