name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  conform:
    name: Conform
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: siderolabs/conform@v0.1.0-alpha.29
