name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  conform:
    name: Conform
    runs-on: ubuntu-latest
    steps:
      - uses: siderolabs/conform@v0.1.0-alpha.29
