name: shellcheck@latest
# This workflow is triggered ONLY on pushes to the repository
on: push
jobs:
  shellcheck:
    name: ShellCheck
    # Test against macOS and NOT Linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
